config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do # the parent
    resources :posts, except: [:index] # children. #index is no longer an available view since we now list them in the parents #show view
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'about' => "welcome#about"
  
  root 'welcome#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    before_action :require_sign_in
    
    def create
       
       post = Post.find(params[:post_id])
       favorite = current_user.favorites.build(post: post)
       
       if favorite.save
           flash[:notice] = "Post favorited."
       else
           flash[:alert] = "Favoriting failed."
       end
       
       redirect_to [post.topic, post]
       
    end
    
    def destroy
        
        post = Post.find(params[:post_id])
        favorite = current_user.favorites.find(params[:id])
        
        if favorite.destroy
            flash[:notice] = "Post unfavorited."
        else
            flash[:alert] = "Unfavoriting failed."
        end
            redirect_to [post.topic, post]
    end
    
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if favorite = current_user.favorite_for(post) %>

    <%= link_to [post,favorite], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unfavorite
    <% end %>
<% else %>
    <%= link_to [post, Favorite.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Favorite
    <% end %>
<% end %>

app/views/favorites/_favorited.html.erb
<% post = Post.find(favorite.id) %>
<% post_author_id = Post.find(favorite.id).user_id %>
<div class="media">
    <div class="media-left">
        <%= image_tag User.find(post_author_id).avatar_url(30), class: 'gravatar' %>
    </div>
    <div class="media-left">
        <small><%= link_to post.title, topic_post_path(post.topic_id, post) %><br />
            Author: <%= link_to User.find(post_author_id).name, user_path(post_author_id)%><br/>
                Votes: <%= Post.find(favorite.id).votes.count %> / Comments: <%= Post.find(favorite.id).comments.count %>
        </small>
    </div>
</div>