config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do # the parent
    resources :posts, except: [:index] # children. #index is no longer an available view since we now list them in the parents #show view
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'about' => "welcome#about"
  
  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
  def faq
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About</h1>
<p>This online Reddit clone is a 32-point lesson.<br>It incorporates TDD (test driven development) and BDD (behavior driven development) to build and maintain this online application it's been quite the adventure getting used to the in's and out's of Ruby on Rails</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erg</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1>Bloccit</h1>
    <p>Bloccit is a resource for sharing links with your friends!</p>
    <% if !current_user %>
        <p>
            <%= link_to "Sign In", new_session_path, class: 'btn btn-primary' %> or
            <%= link_to "Sign up", new_user_path, class: 'btn btn-primary' %> today!
        </p>
    <% end %>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Solves world hunger</h2>
        <p>Bloccit will deliver food and water to those in need, all over the world.</p>
    </div>
    <div class="col-md-4">
        <h2>Eliminates poverty</h2>
        <p>Bloccit will deliver money and education to those in need, all over the world.</p>
    </div>
    <div class="col-md-4">
        <h2>Makes you better looking</h2>
        <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
    </div>
</div>