config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do # the parent
    resources :posts, except: [:index] # children. #index is no longer an available view since we now list them in the parents #show view
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'about' => "welcome#about"
  
  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :topic
    belongs_to :user #make sure to add [has_many :posts] to the user model.
    has_many :comments, dependent: :destroy 
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    
    # due to belongs_to and having a user_id & topic_id in the Post table we need to make sure
    # a post has both a topic and author(user)
    validates :topic, presence: true
    validates :user, presence: true
    
    # scoping posts allows us to retrieve and order posts by their created_at date in descending order
    default_scope { order('rank DESC') } # <-- update our default scope to filter by post rank as opposed to created_at.
    
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
    def up_votes
        # SQL query for any vote which is a value of 1
        votes.where(value: 1).count
    end
    
    def down_votes
        # SQL query for any vote which is a value of -1
        votes.where(value: -1).count
    end
    
    def points
        # utilize ActiveRecord #sum method
        votes.sum(:value)
    end
    
    def update_rank
       age_in_days = (created_at - Time.new(1970,1,1)) / 1.days.seconds
       new_rank = points + age_in_days
       update_attribute(:rank, new_rank)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_sign_in, except: :show
  
  before_action :authorize_delete, only: :destroy
  
  before_action :authorize_edit, only: :edit

  def show
      @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user
    
    if @post.save
      flash[:notice] = "Post was saved & favorited"
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    
    if @post.save
      flash[:notice] = "Post was succesfully updated"
      # note: rails has the ability to generate a route from array 
      # the following would create /topics/topic_id/posts/post_id
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error updating the post. Please try again."
      render :edit
    end
    
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      flash[:notice] = "post \"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "error deleting post. Please try again"
      render :show
    end
    
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body)
  end
  
  def authorize_delete
    # POST MUST EXIST TO BE DELETED
    post = Post.find(params[:id])
    
    unless current_user == post.user || current_user.admin?
      flash[:alert] = "You are not the author or admin to do that."
      redirect_to [post.topic, post]
    end
  end
  
  def authorize_edit
    # POST MUST EXIST TO BE EDITED
    post = Post.find(params[:id])
    
    unless current_user == post.user || current_user.admin? || current_user.moderator?
      flash[:alert] = "As a #{current_user.role}, you are not the authorized for such a request."
      redirect_to [post.topic, post]
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
    
    def user_is_authorized_for_post?(post)
       current_user && ( current_user == post.user || current_user.admin? || current_user.moderator? )
    end
    
    def user_is_authorized_to_destroy?(post)
       current_user && (current_user == post.user || current_user.admin?)
    end
    
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
    <% if post.errors.any? %>
        <div class="alert alert-danger">
            <h4><%= pluralize(post.errors.count, "error") %>.</h4>
            <ul>
                <% post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    <% end %>
    <%= form_group_tag(post.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    <% end %>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
    <%= render partial: 'votes/voter', locals: {post: post} %>
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(post.topic, post) %>
        </h4>
        <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
            <%= post.comments.count %> Comments
        </small>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes</li>
            <li>Don't use the letter 'A'</li>
            <li>The incessant use of Hashtags will get you bannded</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes</li>
            <li>Don't use the letter 'A'</li>
            <li>The incessant use of Hashtags will get you bannded</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
</div>

app/views/posts/show.html.erb
<div>
    <%= render partial: 'votes/voter', locals: { post: @post } %>
    <h1>
        <div class="col-md-8">
            <%= @post.title %>
            <% if user_is_authorized_for_post?(@post) %>
                <%= link_to "", edit_topic_post_path(@post.topic, @post), class:"glyphicon glyphicon-edit glyphicon-post", title: "edit post" %>
                <% if user_is_authorized_to_destroy?(@post) %>
                    <%= link_to "", [@post.topic, @post], method: :delete, class:"glyphicon glyphicon-trash glyphicon-post", title: "delete post", data: {confirm: 'Are you sure you\'d like to delete this post?'}  %>
                <% end %>
            <% end %>
        </div>
    <div class="col-md-2">
        <h3>
            <%= pluralize(@post.points, 'point') %>
            <div>
                <small>
                    <%= pluralize(@post.up_votes, 'up vote') %>, 
                    <%= pluralize(@post.down_votes, 'down vote') %>
                </small>
            </div>
        </h3>
        <% if current_user %>
            <%= render partial: 'favorites/favorite', locals: {post: @post} %>
        <% end %>
    </div>
        <small class="col-md-8">
            submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-md-8">
        <h4>
            <p><%= @post.body %></p>
        </h4>
        <div>
            <h3>Comments</h3>
            <%= render @post.comments %>
        </div>
        <% if current_user %>
            <%= render 'comments/form', comment: Comment.new, post: @post %>
        <% end %>
    </div>
</div>